eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
      - id: CART-SERVICE
        uri: http://localhost:8090
        predicates:
        - Path=/cart/**
          
